	$(function() {
		var citylist = [{
				"name": "澳门",
				"id": 1129,
				"code": "A",
				"children": [{
					"name": "澳门",
					"id": 1149,
					"code": "A"
				}]
			}, {
				"name": "安徽省",
				"id": 366,
				"code": "A",
				"children": [{
					"name": "安庆",
					"id": 381,
					"code": "A"
				}, {
					"name": "蚌埠",
					"id": 382,
					"code": "B"
				}, {
					"name": "亳州",
					"id": 393,
					"code": "B"
				}, {
					"name": "滁州",
					"id": 389,
					"code": "C"
				}, {
					"name": "池州",
					"id": 394,
					"code": "C"
				}, {
					"name": "巢湖",
					"id": 396,
					"code": "C"
				}, {
					"name": "凤阳",
					"id": 397,
					"code": "F"
				}, {
					"name": "阜阳",
					"id": 390,
					"code": "F"
				}, {
					"name": "广德",
					"id": 398,
					"code": "G"
				}, {
					"name": "合肥",
					"id": 367,
					"code": "H"
				}, {
					"name": "黄山",
					"id": 388,
					"code": "H"
				}, {
					"name": "淮南",
					"id": 384,
					"code": "H"
				}, {
					"name": "淮北",
					"id": 386,
					"code": "H"
				}, {
					"name": "六安",
					"id": 392,
					"code": "L"
				}, {
					"name": "马鞍山",
					"id": 385,
					"code": "M"
				}, {
					"name": "宿松",
					"id": 399,
					"code": "S"
				}, {
					"name": "宿州",
					"id": 391,
					"code": "S"
				}, {
					"name": "铜陵",
					"id": 387,
					"code": "T"
				}, {
					"name": "芜湖",
					"id": 383,
					"code": "W"
				}, {
					"name": "宣城",
					"id": 395,
					"code": "X"
				}]
			}, {
				"name": "北京",
				"id": 1148,
				"code": "B",
				"children": [{
					"name": "北京",
					"id": 7,
					"code": "B"
				}]
			}, {
				"name": "重庆",
				"id": 1152,
				"code": "C",
				"children": [{
					"name": "重庆",
					"id": 67,
					"code": "C"
				}]
			}, {
				"name": "福建省",
				"id": 400,
				"code": "F",
				"children": [{
					"name": "福州",
					"id": 401,
					"code": "F"
				}, {
					"name": "福安",
					"id": 430,
					"code": "F"
				}, {
					"name": "晋江",
					"id": 431,
					"code": "J"
				}, {
					"name": "龙岩",
					"id": 427,
					"code": "L"
				}, {
					"name": "宁德",
					"id": 428,
					"code": "N"
				}, {
					"name": "南平",
					"id": 426,
					"code": "N"
				}, {
					"name": "莆田",
					"id": 424,
					"code": "P"
				}, {
					"name": "泉港区",
					"id": 429,
					"code": "Q"
				}, {
					"name": "泉州",
					"id": 415,
					"code": "Q"
				}, {
					"name": "三明",
					"id": 425,
					"code": "S"
				}, {
					"name": "厦门",
					"id": 416,
					"code": "X"
				}, {
					"name": "漳州",
					"id": 423,
					"code": "Z"
				}]
			}, {
				"name": "广东省",
				"id": 110,
				"code": "G",
				"children": [{
					"name": "潮州",
					"id": 125,
					"code": "C"
				}, {
					"name": "东莞",
					"id": 126,
					"code": "D"
				}, {
					"name": "佛山",
					"id": 160,
					"code": "F"
				}, {
					"name": "广州",
					"id": 111,
					"code": "G"
				}, {
					"name": "河源",
					"id": 200,
					"code": "H"
				}, {
					"name": "鹤山",
					"id": 208,
					"code": "H"
				}, {
					"name": "惠州",
					"id": 171,
					"code": "H"
				}, {
					"name": "阳江",
					"id": 195,
					"code": "J"
				}, {
					"name": "揭阳",
					"id": 201,
					"code": "J"
				}, {
					"name": "江门",
					"id": 194,
					"code": "J"
				}, {
					"name": "开平",
					"id": 203,
					"code": "K"
				}, {
					"name": "龙川",
					"id": 207,
					"code": "L"
				}, {
					"name": "梅州",
					"id": 198,
					"code": "M"
				}, {
					"name": "茂名",
					"id": 197,
					"code": "M"
				}, {
					"name": "南沙",
					"id": 206,
					"code": "N"
				}, {
					"name": "普宁",
					"id": 205,
					"code": "P"
				}, {
					"name": "清远",
					"id": 172,
					"code": "Q"
				}, {
					"name": "深圳",
					"id": 174,
					"code": "S"
				}, {
					"name": "顺德",
					"id": 185,
					"code": "S"
				}, {
					"name": "汕头",
					"id": 173,
					"code": "S"
				}, {
					"name": "汕尾",
					"id": 199,
					"code": "S"
				}, {
					"name": "韶关",
					"id": 196,
					"code": "S"
				}, {
					"name": "台山",
					"id": 204,
					"code": "T"
				}, {
					"name": "云浮",
					"id": 202,
					"code": "Y"
				}, {
					"name": "湛江",
					"id": 186,
					"code": "Z"
				}, {
					"name": "肇庆",
					"id": 187,
					"code": "Z"
				}, {
					"name": "中山",
					"id": 188,
					"code": "Z"
				}, {
					"name": "珠海",
					"id": 189,
					"code": "Z"
				}]
			}, {
				"name": "贵州省",
				"id": 482,
				"code": "G",
				"children": [{
					"name": "安顺",
					"id": 498,
					"code": "A"
				}, {
					"name": "毕节",
					"id": 499,
					"code": "B"
				}, {
					"name": "贵阳",
					"id": 483,
					"code": "G"
				}, {
					"name": "六盘水",
					"id": 497,
					"code": "L"
				}, {
					"name": "黔西南",
					"id": 501,
					"code": "Q"
				}, {
					"name": "黔东南",
					"id": 502,
					"code": "Q"
				}, {
					"name": "黔南",
					"id": 503,
					"code": "Q"
				}, {
					"name": "铜仁",
					"id": 500,
					"code": "T"
				}, {
					"name": "遵义",
					"id": 496,
					"code": "Z"
				}]
			}, {
				"name": "广西省",
				"id": 455,
				"code": "G",
				"children": [{
					"name": "北海",
					"id": 469,
					"code": "B"
				}, {
					"name": "百色",
					"id": 477,
					"code": "B"
				}, {
					"name": "崇左",
					"id": 474,
					"code": "C"
				}, {
					"name": "防城港",
					"id": 476,
					"code": "F"
				}, {
					"name": "贵港",
					"id": 481,
					"code": "G"
				}, {
					"name": "桂林",
					"id": 470,
					"code": "G"
				}, {
					"name": "河池",
					"id": 480,
					"code": "H"
				}, {
					"name": "贺州",
					"id": 479,
					"code": "H"
				}, {
					"name": "来宾",
					"id": 475,
					"code": "L"
				}, {
					"name": "柳州",
					"id": 471,
					"code": "L"
				}, {
					"name": "南宁",
					"id": 456,
					"code": "N"
				}, {
					"name": "钦州",
					"id": 478,
					"code": "Q"
				}, {
					"name": "梧州",
					"id": 473,
					"code": "W"
				}, {
					"name": "玉林",
					"id": 472,
					"code": "Y"
				}]
			}, {
				"name": "甘肃省",
				"id": 432,
				"code": "G",
				"children": [{
					"name": "白银",
					"id": 445,
					"code": "B"
				}, {
					"name": "定西",
					"id": 449,
					"code": "D"
				}, {
					"name": "甘南",
					"id": 454,
					"code": "G"
				}, {
					"name": "嘉峪关",
					"id": 442,
					"code": "J"
				}, {
					"name": "酒泉",
					"id": 443,
					"code": "J"
				}, {
					"name": "金昌",
					"id": 444,
					"code": "J"
				}, {
					"name": "临夏",
					"id": 453,
					"code": "L"
				}, {
					"name": "陇南",
					"id": 450,
					"code": "L"
				}, {
					"name": "兰州",
					"id": 433,
					"code": "L"
				}, {
					"name": "平凉",
					"id": 451,
					"code": "P"
				}, {
					"name": "庆阳",
					"id": 452,
					"code": "Q"
				}, {
					"name": "天水",
					"id": 446,
					"code": "T"
				}, {
					"name": "武威",
					"id": 448,
					"code": "W"
				}, {
					"name": "张掖",
					"id": 447,
					"code": "Z"
				}]
			}, {
				"name": "湖南省",
				"id": 693,
				"code": "H",
				"children": [{
					"name": "长沙",
					"id": 694,
					"code": "C"
				}, {
					"name": "常德",
					"id": 707,
					"code": "C"
				}, {
					"name": "郴州",
					"id": 710,
					"code": "C"
				}, {
					"name": "怀化",
					"id": 716,
					"code": "H"
				}, {
					"name": "衡阳",
					"id": 708,
					"code": "H"
				}, {
					"name": "娄底",
					"id": 714,
					"code": "L"
				}, {
					"name": "邵阳",
					"id": 712,
					"code": "S"
				}, {
					"name": "湘西",
					"id": 717,
					"code": "X"
				}, {
					"name": "湘潭",
					"id": 705,
					"code": "X"
				}, {
					"name": "益阳",
					"id": 709,
					"code": "Y"
				}, {
					"name": "永州",
					"id": 715,
					"code": "Y"
				}, {
					"name": "岳阳",
					"id": 711,
					"code": "Y"
				}, {
					"name": "张家界",
					"id": 713,
					"code": "Z"
				}, {
					"name": "株洲",
					"id": 706,
					"code": "Z"
				}]
			}, {
				"name": "湖北省",
				"id": 658,
				"code": "H",
				"children": [{
					"name": "恩施",
					"id": 689,
					"code": "E"
				}, {
					"name": "鄂州",
					"id": 681,
					"code": "E"
				}, {
					"name": "公安",
					"id": 690,
					"code": "G"
				}, {
					"name": "黄冈",
					"id": 682,
					"code": "H"
				}, {
					"name": "黄石",
					"id": 680,
					"code": "H"
				}, {
					"name": "荆州",
					"id": 679,
					"code": "J"
				}, {
					"name": "荆门",
					"id": 678,
					"code": "J"
				}, {
					"name": "潜江",
					"id": 677,
					"code": "Q"
				}, {
					"name": "神农架",
					"id": 688,
					"code": "S"
				}, {
					"name": "随州",
					"id": 685,
					"code": "S"
				}, {
					"name": "十堰",
					"id": 674,
					"code": "S"
				}, {
					"name": "天门",
					"id": 687,
					"code": "T"
				}, {
					"name": "武穴",
					"id": 691,
					"code": "W"
				}, {
					"name": "武汉",
					"id": 659,
					"code": "W"
				}, {
					"name": "仙桃",
					"id": 686,
					"code": "X"
				}, {
					"name": "咸宁",
					"id": 684,
					"code": "X"
				}, {
					"name": "孝感",
					"id": 683,
					"code": "X"
				}, {
					"name": "襄阳",
					"id": 675,
					"code": "X"
				}, {
					"name": "宜昌",
					"id": 676,
					"code": "Y"
				}, {
					"name": "宜城",
					"id": 692,
					"code": "Y"
				}]
			}, {
				"name": "黑龙江省",
				"id": 619,
				"code": "H",
				"children": [{
					"name": "安达",
					"id": 653,
					"code": "A"
				}, {
					"name": "大庆",
					"id": 641,
					"code": "D"
				}, {
					"name": "大兴安岭",
					"id": 652,
					"code": "D"
				}, {
					"name": "哈尔滨",
					"id": 620,
					"code": "H"
				}, {
					"name": "鹤岗",
					"id": 646,
					"code": "H"
				}, {
					"name": "黑河",
					"id": 650,
					"code": "H"
				}, {
					"name": "佳木斯",
					"id": 642,
					"code": "J"
				}, {
					"name": "鸡西",
					"id": 645,
					"code": "J"
				}, {
					"name": "牡丹江",
					"id": 643,
					"code": "M"
				}, {
					"name": "七台河",
					"id": 649,
					"code": "Q"
				}, {
					"name": "齐齐哈尔",
					"id": 644,
					"code": "Q"
				}, {
					"name": "绥化",
					"id": 651,
					"code": "S"
				}, {
					"name": "双鸭山",
					"id": 647,
					"code": "S"
				}, {
					"name": "双城",
					"id": 654,
					"code": "S"
				}, {
					"name": "尚志",
					"id": 655,
					"code": "S"
				}, {
					"name": "绥芬河",
					"id": 656,
					"code": "S"
				}, {
					"name": "伊春",
					"id": 648,
					"code": "Y"
				}, {
					"name": "肇东",
					"id": 657,
					"code": "Z"
				}]
			}, {
				"name": "河南省",
				"id": 581,
				"code": "H",
				"children": [{
					"name": "安阳",
					"id": 603,
					"code": "A"
				}, {
					"name": "长葛",
					"id": 618,
					"code": "C"
				}, {
					"name": "鹤壁",
					"id": 611,
					"code": "H"
				}, {
					"name": "济源",
					"id": 616,
					"code": "J"
				}, {
					"name": "焦作",
					"id": 606,
					"code": "J"
				}, {
					"name": "开封",
					"id": 600,
					"code": "K"
				}, {
					"name": "漯河",
					"id": 609,
					"code": "L"
				}, {
					"name": "洛阳",
					"id": 601,
					"code": "L"
				}, {
					"name": "南阳",
					"id": 614,
					"code": "N"
				}, {
					"name": "濮阳",
					"id": 607,
					"code": "P"
				}, {
					"name": "平顶山",
					"id": 604,
					"code": "P"
				}, {
					"name": "商丘",
					"id": 602,
					"code": "S"
				}, {
					"name": "三门峡",
					"id": 610,
					"code": "S"
				}, {
					"name": "西平",
					"id": 617,
					"code": "X"
				}, {
					"name": "新乡",
					"id": 605,
					"code": "X"
				}, {
					"name": "许昌",
					"id": 608,
					"code": "X"
				}, {
					"name": "信阳",
					"id": 615,
					"code": "X"
				}, {
					"name": "驻马店",
					"id": 613,
					"code": "Z"
				}, {
					"name": "周口",
					"id": 612,
					"code": "Z"
				}, {
					"name": "郑州",
					"id": 582,
					"code": "Z"
				}]
			}, {
				"name": "海南省",
				"id": 504,
				"code": "H",
				"children": [{
					"name": "白沙",
					"id": 536,
					"code": "B"
				}, {
					"name": "保亭",
					"id": 535,
					"code": "B"
				}, {
					"name": "昌江",
					"id": 537,
					"code": "C"
				}, {
					"name": "澄迈",
					"id": 532,
					"code": "C"
				}, {
					"name": "定安",
					"id": 530,
					"code": "D"
				}, {
					"name": "东方",
					"id": 528,
					"code": "D"
				}, {
					"name": "儋州",
					"id": 527,
					"code": "D"
				}, {
					"name": "海口",
					"id": 505,
					"code": "H"
				}, {
					"name": "陵水",
					"id": 539,
					"code": "L"
				}, {
					"name": "乐东",
					"id": 538,
					"code": "L"
				}, {
					"name": "临高",
					"id": 533,
					"code": "L"
				}, {
					"name": "琼中",
					"id": 534,
					"code": "Q"
				}, {
					"name": "琼海",
					"id": 525,
					"code": "Q"
				}, {
					"name": "三沙",
					"id": 522,
					"code": "S"
				}, {
					"name": "三亚",
					"id": 521,
					"code": "S"
				}, {
					"name": "屯昌",
					"id": 531,
					"code": "T"
				}, {
					"name": "文昌",
					"id": 524,
					"code": "W"
				}, {
					"name": "五指山",
					"id": 529,
					"code": "W"
				}, {
					"name": "万宁",
					"id": 526,
					"code": "W"
				}, {
					"name": "洋浦区",
					"id": 523,
					"code": "Y"
				}]
			}, {
				"name": "河北省",
				"id": 540,
				"code": "H",
				"children": [{
					"name": "保定",
					"id": 566,
					"code": "B"
				}, {
					"name": "承德",
					"id": 567,
					"code": "C"
				}, {
					"name": "沧州",
					"id": 574,
					"code": "C"
				}, {
					"name": "固安",
					"id": 577,
					"code": "G"
				}, {
					"name": "邯郸",
					"id": 568,
					"code": "H"
				}, {
					"name": "衡水",
					"id": 575,
					"code": "H"
				}, {
					"name": "廊坊",
					"id": 569,
					"code": "L"
				}, {
					"name": "秦皇岛",
					"id": 570,
					"code": "Q"
				}, {
					"name": "石家庄",
					"id": 541,
					"code": "S"
				}, {
					"name": "三河",
					"id": 580,
					"code": "S"
				}, {
					"name": "唐山",
					"id": 571,
					"code": "T"
				}, {
					"name": "香河",
					"id": 579,
					"code": "X"
				}, {
					"name": "邢台",
					"id": 573,
					"code": "X"
				}, {
					"name": "燕郊",
					"id": 576,
					"code": "Y"
				}, {
					"name": "张家口",
					"id": 572,
					"code": "Z"
				}, {
					"name": "遵化",
					"id": 578,
					"code": "Z"
				}]
			}, {
				"name": "吉林省",
				"id": 718,
				"code": "J",
				"children": [{
					"name": "白山",
					"id": 741,
					"code": "B"
				}, {
					"name": "白城",
					"id": 743,
					"code": "B"
				}, {
					"name": "长春",
					"id": 719,
					"code": "C"
				}, {
					"name": "公主岭",
					"id": 746,
					"code": "G"
				}, {
					"name": "吉林市",
					"id": 737,
					"code": "J"
				}, {
					"name": "辽源",
					"id": 739,
					"code": "L"
				}, {
					"name": "四平",
					"id": 738,
					"code": "S"
				}, {
					"name": "松原",
					"id": 742,
					"code": "S"
				}, {
					"name": "通化",
					"id": 740,
					"code": "T"
				}, {
					"name": "延吉",
					"id": 744,
					"code": "Y"
				}, {
					"name": "延边",
					"id": 745,
					"code": "Y"
				}]
			}, {
				"name": "江西省",
				"id": 747,
				"code": "J",
				"children": [{
					"name": "抚州",
					"id": 767,
					"code": "F"
				}, {
					"name": "赣州",
					"id": 763,
					"code": "G"
				}, {
					"name": "九江",
					"id": 762,
					"code": "J"
				}, {
					"name": "吉安",
					"id": 765,
					"code": "J"
				}, {
					"name": "景德镇",
					"id": 768,
					"code": "J"
				}, {
					"name": "南昌",
					"id": 748,
					"code": "N"
				}, {
					"name": "萍乡",
					"id": 769,
					"code": "P"
				}, {
					"name": "上饶",
					"id": 766,
					"code": "S"
				}, {
					"name": "新余",
					"id": 770,
					"code": "X"
				}, {
					"name": "宜春",
					"id": 764,
					"code": "Y"
				}, {
					"name": "鹰潭",
					"id": 771,
					"code": "Y"
				}]
			}, {
				"name": "江苏省",
				"id": 209,
				"code": "J",
				"children": [{
					"name": "常熟",
					"id": 225,
					"code": "C"
				}, {
					"name": "常州",
					"id": 226,
					"code": "C"
				}, {
					"name": "丹阳",
					"id": 283,
					"code": "D"
				}, {
					"name": "高邮",
					"id": 291,
					"code": "G"
				}, {
					"name": "淮安",
					"id": 277,
					"code": "H"
				}, {
					"name": "江阴",
					"id": 282,
					"code": "J"
				}, {
					"name": "靖江",
					"id": 287,
					"code": "J"
				}, {
					"name": "句容",
					"id": 288,
					"code": "J"
				}, {
					"name": "金湖",
					"id": 295,
					"code": "J"
				}, {
					"name": "昆山",
					"id": 235,
					"code": "K"
				}, {
					"name": "溧阳",
					"id": 284,
					"code": "L"
				}, {
					"name": "连云港",
					"id": 236,
					"code": "L"
				}, {
					"name": "南京",
					"id": 210,
					"code": "N"
				}, {
					"name": "南通",
					"id": 237,
					"code": "N"
				}, {
					"name": "启东",
					"id": 292,
					"code": "Q"
				}, {
					"name": "如皋",
					"id": 289,
					"code": "R"
				}, {
					"name": "宿迁",
					"id": 280,
					"code": "S"
				}, {
					"name": "苏州",
					"id": 238,
					"code": "S"
				}, {
					"name": "通州",
					"id": 294,
					"code": "T"
				}, {
					"name": "太仓",
					"id": 263,
					"code": "T"
				}, {
					"name": "泰兴",
					"id": 285,
					"code": "T"
				}, {
					"name": "泰州",
					"id": 279,
					"code": "T"
				}, {
					"name": "无锡",
					"id": 264,
					"code": "W"
				}, {
					"name": "徐州",
					"id": 274,
					"code": "X"
				}, {
					"name": "盱眙",
					"id": 293,
					"code": "X"
				}, {
					"name": "宜兴",
					"id": 286,
					"code": "Y"
				}, {
					"name": "盐城",
					"id": 278,
					"code": "Y"
				}, {
					"name": "扬中",
					"id": 290,
					"code": "Y"
				}, {
					"name": "扬州",
					"id": 275,
					"code": "Y"
				}, {
					"name": "镇江",
					"id": 276,
					"code": "Z"
				}, {
					"name": "张家港",
					"id": 281,
					"code": "Z"
				}]
			}, {
				"name": "辽宁省",
				"id": 772,
				"code": "L",
				"children": [{
					"name": "鞍山",
					"id": 788,
					"code": "A"
				}, {
					"name": "本溪",
					"id": 805,
					"code": "B"
				}, {
					"name": "昌图",
					"id": 816,
					"code": "C"
				}, {
					"name": "朝阳",
					"id": 813,
					"code": "C"
				}, {
					"name": "丹东",
					"id": 806,
					"code": "D"
				}, {
					"name": "大连",
					"id": 789,
					"code": "D"
				}, {
					"name": "抚顺",
					"id": 804,
					"code": "F"
				}, {
					"name": "阜新",
					"id": 809,
					"code": "F"
				}, {
					"name": "葫芦岛",
					"id": 803,
					"code": "H"
				}, {
					"name": "海城",
					"id": 815,
					"code": "H"
				}, {
					"name": "锦州",
					"id": 807,
					"code": "J"
				}, {
					"name": "开原",
					"id": 817,
					"code": "K"
				}, {
					"name": "辽阳",
					"id": 810,
					"code": "L"
				}, {
					"name": "盘锦",
					"id": 811,
					"code": "P"
				}, {
					"name": "沈阳",
					"id": 773,
					"code": "S"
				}, {
					"name": "铁岭",
					"id": 812,
					"code": "T"
				}, {
					"name": "兴城",
					"id": 814,
					"code": "X"
				}, {
					"name": "营口",
					"id": 808,
					"code": "Y"
				}]
			}, {
				"name": "内蒙古",
				"id": 818,
				"code": "N",
				"children": [{
					"name": "呼和浩特",
					"id": 819,
					"code": "H"
				}]
			}, {
				"name": "宁夏",
				"id": 840,
				"code": "N",
				"children": [{
					"name": "固原",
					"id": 854,
					"code": "G"
				}, {
					"name": "石嘴山",
					"id": 852,
					"code": "S"
				}, {
					"name": "吴忠",
					"id": 853,
					"code": "W"
				}, {
					"name": "银川",
					"id": 841,
					"code": "Y"
				}, {
					"name": "中卫",
					"id": 855,
					"code": "Z"
				}]
			}, {
				"name": "青海省",
				"id": 856,
				"code": "Q",
				"children": [{
					"name": "果洛",
					"id": 872,
					"code": "G"
				}, {
					"name": "海东",
					"id": 867,
					"code": "H"
				}, {
					"name": "海西",
					"id": 868,
					"code": "H"
				}, {
					"name": "海北",
					"id": 869,
					"code": "H"
				}, {
					"name": "黄南",
					"id": 870,
					"code": "H"
				}, {
					"name": "海南",
					"id": 871,
					"code": "H"
				}, {
					"name": "西宁",
					"id": 857,
					"code": "X"
				}, {
					"name": "玉树",
					"id": 873,
					"code": "Y"
				}]
			}, {
				"name": "山东省",
				"id": 874,
				"code": "S",
				"children": [{
					"name": "滨州",
					"id": 912,
					"code": "B"
				}, {
					"name": "城阳",
					"id": 919,
					"code": "C"
				}, {
					"name": "德州",
					"id": 888,
					"code": "D"
				}, {
					"name": "东营",
					"id": 889,
					"code": "D"
				}, {
					"name": "肥城",
					"id": 921,
					"code": "F"
				}, {
					"name": "海阳",
					"id": 923,
					"code": "H"
				}, {
					"name": "黄岛",
					"id": 917,
					"code": "H"
				}, {
					"name": "菏泽",
					"id": 914,
					"code": "H"
				}, {
					"name": "胶州",
					"id": 924,
					"code": "J"
				}, {
					"name": "胶南",
					"id": 925,
					"code": "J"
				}, {
					"name": "即墨",
					"id": 920,
					"code": "J"
				}, {
					"name": "济宁",
					"id": 890,
					"code": "J"
				}, {
					"name": "济南",
					"id": 875,
					"code": "J"
				}, {
					"name": "莱芜",
					"id": 915,
					"code": "L"
				}, {
					"name": "聊城",
					"id": 913,
					"code": "L"
				}, {
					"name": "莱西",
					"id": 927,
					"code": "L"
				}, {
					"name": "临沂",
					"id": 891,
					"code": "L"
				}, {
					"name": "平度",
					"id": 926,
					"code": "P"
				}, {
					"name": "青岛",
					"id": 892,
					"code": "Q"
				}, {
					"name": "荣成",
					"id": 916,
					"code": "R"
				}, {
					"name": "乳山",
					"id": 918,
					"code": "R"
				}, {
					"name": "日照",
					"id": 905,
					"code": "R"
				}, {
					"name": "泰安",
					"id": 906,
					"code": "T"
				}, {
					"name": "威海",
					"id": 907,
					"code": "W"
				}, {
					"name": "潍坊",
					"id": 908,
					"code": "W"
				}, {
					"name": "兖州",
					"id": 922,
					"code": "Y"
				}, {
					"name": "烟台",
					"id": 909,
					"code": "Y"
				}, {
					"name": "淄博",
					"id": 910,
					"code": "Z"
				}, {
					"name": "枣庄",
					"id": 911,
					"code": "Z"
				}]
			}, {
				"name": "山西省",
				"id": 928,
				"code": "S",
				"children": [{
					"name": "长治",
					"id": 946,
					"code": "C"
				}, {
					"name": "大同",
					"id": 943,
					"code": "D"
				}, {
					"name": "和顺",
					"id": 954,
					"code": "H"
				}, {
					"name": "晋中",
					"id": 950,
					"code": "J"
				}, {
					"name": "晋城",
					"id": 948,
					"code": "J"
				}, {
					"name": "临汾",
					"id": 944,
					"code": "L"
				}, {
					"name": "吕梁",
					"id": 952,
					"code": "L"
				}, {
					"name": "朔州",
					"id": 949,
					"code": "S"
				}, {
					"name": "太原",
					"id": 929,
					"code": "T"
				}, {
					"name": "忻州",
					"id": 951,
					"code": "X"
				}, {
					"name": "阳泉",
					"id": 947,
					"code": "Y"
				}, {
					"name": "运城",
					"id": 945,
					"code": "Y"
				}, {
					"name": "永济",
					"id": 953,
					"code": "Y"
				}]
			}, {
				"name": "陕西省",
				"id": 955,
				"code": "S",
				"children": [{
					"name": "安康",
					"id": 977,
					"code": "A"
				}, {
					"name": "宝鸡",
					"id": 972,
					"code": "B"
				}, {
					"name": "汉中",
					"id": 976,
					"code": "H"
				}, {
					"name": "商洛",
					"id": 978,
					"code": "S"
				}, {
					"name": "铜川",
					"id": 974,
					"code": "T"
				}, {
					"name": "渭南",
					"id": 975,
					"code": "W"
				}, {
					"name": "西安",
					"id": 956,
					"code": "X"
				}, {
					"name": "咸阳",
					"id": 973,
					"code": "X"
				}, {
					"name": "兴平",
					"id": 982,
					"code": "X"
				}, {
					"name": "延安",
					"id": 979,
					"code": "Y"
				}, {
					"name": "榆林",
					"id": 980,
					"code": "Y"
				}, {
					"name": "杨凌",
					"id": 981,
					"code": "Y"
				}]
			}, {
				"name": "四川省",
				"id": 983,
				"code": "S",
				"children": [{
					"name": "阿坝",
					"id": 1026,
					"code": "A"
				}, {
					"name": "巴中",
					"id": 1022,
					"code": "B"
				}, {
					"name": "成都",
					"id": 984,
					"code": "C"
				}, {
					"name": "德阳",
					"id": 1014,
					"code": "D"
				}, {
					"name": "达州",
					"id": 1020,
					"code": "D"
				}, {
					"name": "峨眉",
					"id": 1028,
					"code": "E"
				}, {
					"name": "甘孜",
					"id": 1025,
					"code": "G"
				}, {
					"name": "广安",
					"id": 1019,
					"code": "G"
				}, {
					"name": "广元",
					"id": 1015,
					"code": "G"
				}, {
					"name": "简阳",
					"id": 1029,
					"code": "J"
				}, {
					"name": "乐山",
					"id": 1007,
					"code": "L"
				}, {
					"name": "凉山",
					"id": 1027,
					"code": "L"
				}, {
					"name": "泸州",
					"id": 1008,
					"code": "L"
				}, {
					"name": "眉山",
					"id": 1018,
					"code": "M"
				}, {
					"name": "绵阳",
					"id": 1009,
					"code": "M"
				}, {
					"name": "南充",
					"id": 1017,
					"code": "N"
				}, {
					"name": "内江",
					"id": 1010,
					"code": "N"
				}, {
					"name": "攀枝花",
					"id": 1013,
					"code": "P"
				}, {
					"name": "遂宁",
					"id": 1016,
					"code": "S"
				}, {
					"name": "西昌",
					"id": 1024,
					"code": "X"
				}, {
					"name": "雅安",
					"id": 1021,
					"code": "Y"
				}, {
					"name": "宜宾",
					"id": 1011,
					"code": "Y"
				}, {
					"name": "自贡",
					"id": 1012,
					"code": "Z"
				}, {
					"name": "资阳",
					"id": 1023,
					"code": "Z"
				}]
			}, {
				"name": "上海",
				"id": 1151,
				"code": "S",
				"children": [{
					"name": "上海",
					"id": 26,
					"code": "S"
				}]
			}, {
				"name": "台湾",
				"id": 1130,
				"code": "T",
				"children": [{
					"name": "高雄",
					"id": 1132,
					"code": "G"
				}, {
					"name": "花莲县",
					"id": 1146,
					"code": "H"
				}, {
					"name": "基隆",
					"id": 1133,
					"code": "J"
				}, {
					"name": "嘉义",
					"id": 1137,
					"code": "J"
				}, {
					"name": "苗栗县",
					"id": 1140,
					"code": "M"
				}, {
					"name": "南投县",
					"id": 1142,
					"code": "N"
				}, {
					"name": "澎湖县",
					"id": 1147,
					"code": "P"
				}, {
					"name": "屏东县",
					"id": 1144,
					"code": "P"
				}, {
					"name": "台东县",
					"id": 1145,
					"code": "T"
				}, {
					"name": "桃园县",
					"id": 1139,
					"code": "T"
				}, {
					"name": "台南",
					"id": 1135,
					"code": "T"
				}, {
					"name": "台中",
					"id": 1134,
					"code": "T"
				}, {
					"name": "台北",
					"id": 1131,
					"code": "T"
				}, {
					"name": "新竹",
					"id": 1136,
					"code": "X"
				}, {
					"name": "宜兰县",
					"id": 1138,
					"code": "Y"
				}, {
					"name": "云林县",
					"id": 1143,
					"code": "Y"
				}, {
					"name": "彰化县",
					"id": 1141,
					"code": "Z"
				}]
			}, {
				"name": "天津",
				"id": 1153,
				"code": "T",
				"children": [{
					"name": "天津",
					"id": 46,
					"code": "T"
				}]
			}, {
				"name": "香港",
				"id": 1110,
				"code": "X",
				"children": [{
					"name": "香港",
					"id": 1150,
					"code": "X"
				}]
			}, {
				"name": "新疆",
				"id": 1046,
				"code": "X",
				"children": [{
					"name": "阿勒泰",
					"id": 1069,
					"code": "A"
				}, {
					"name": "阿克苏",
					"id": 1062,
					"code": "A"
				}, {
					"name": "阿拉尔",
					"id": 1065,
					"code": "A"
				}, {
					"name": "博尔塔拉",
					"id": 1074,
					"code": "B"
				}, {
					"name": "巴音郭楞",
					"id": 1073,
					"code": "B"
				}, {
					"name": "昌吉",
					"id": 1068,
					"code": "C"
				}, {
					"name": "和田",
					"id": 1072,
					"code": "H"
				}, {
					"name": "哈密",
					"id": 1063,
					"code": "H"
				}, {
					"name": "奎屯市",
					"id": 1075,
					"code": "K"
				}, {
					"name": "克州",
					"id": 1077,
					"code": "K"
				}, {
					"name": "喀什",
					"id": 1059,
					"code": "K"
				}, {
					"name": "克拉玛依",
					"id": 1060,
					"code": "K"
				}, {
					"name": "石河子",
					"id": 1064,
					"code": "S"
				}, {
					"name": "图木舒克",
					"id": 1067,
					"code": "T"
				}, {
					"name": "吐鲁番",
					"id": 1070,
					"code": "T"
				}, {
					"name": "塔城",
					"id": 1071,
					"code": "T"
				}, {
					"name": "乌苏",
					"id": 1076,
					"code": "W"
				}, {
					"name": "乌鲁木齐",
					"id": 1047,
					"code": "W"
				}, {
					"name": "五家渠",
					"id": 1066,
					"code": "W"
				}, {
					"name": "伊犁",
					"id": 1061,
					"code": "Y"
				}]
			}, {
				"name": "西藏",
				"id": 1030,
				"code": "X",
				"children": [{
					"name": "阿里",
					"id": 1045,
					"code": "A"
				}, {
					"name": "昌都",
					"id": 1043,
					"code": "C"
				}, {
					"name": "拉萨",
					"id": 1031,
					"code": "L"
				}, {
					"name": "林芝",
					"id": 1041,
					"code": "L"
				}, {
					"name": "那曲",
					"id": 1044,
					"code": "N"
				}, {
					"name": "日喀则",
					"id": 1040,
					"code": "R"
				}, {
					"name": "山南",
					"id": 1042,
					"code": "S"
				}]
			}, {
				"name": "云南省",
				"id": 1078,
				"code": "Y",
				"children": [{
					"name": "保山",
					"id": 1098,
					"code": "B"
				}, {
					"name": "楚雄",
					"id": 1106,
					"code": "C"
				}, {
					"name": "大理",
					"id": 1094,
					"code": "D"
				}, {
					"name": "迪庆",
					"id": 1108,
					"code": "D"
				}, {
					"name": "德宏",
					"id": 1105,
					"code": "D"
				}, {
					"name": "红河",
					"id": 1102,
					"code": "H"
				}, {
					"name": "昆明",
					"id": 1079,
					"code": "K"
				}, {
					"name": "临沧",
					"id": 1101,
					"code": "L"
				}, {
					"name": "丽江",
					"id": 1095,
					"code": "L"
				}, {
					"name": "怒江",
					"id": 1107,
					"code": "N"
				}, {
					"name": "普洱",
					"id": 1100,
					"code": "P"
				}, {
					"name": "曲靖",
					"id": 1097,
					"code": "Q"
				}, {
					"name": "思茅",
					"id": 1109,
					"code": "S"
				}, {
					"name": "文山",
					"id": 1103,
					"code": "W"
				}, {
					"name": "西双版纳",
					"id": 1104,
					"code": "X"
				}, {
					"name": "玉溪",
					"id": 1096,
					"code": "Y"
				}, {
					"name": "昭通",
					"id": 1099,
					"code": "Z"
				}]
			}, {
				"name": "浙江省",
				"id": 296,
				"code": "Z",
				"children": [{
					"name": "慈溪",
					"id": 352,
					"code": "C"
				}, {
					"name": "东阳",
					"id": 349,
					"code": "D"
				}, {
					"name": "德清",
					"id": 362,
					"code": "D"
				}, {
					"name": "方家山",
					"id": 364,
					"code": "F"
				}, {
					"name": "杭州",
					"id": 297,
					"code": "H"
				}, {
					"name": "海宁",
					"id": 345,
					"code": "H"
				}, {
					"name": "湖州",
					"id": 339,
					"code": "H"
				}, {
					"name": "嘉兴",
					"id": 340,
					"code": "J"
				}, {
					"name": "嘉善",
					"id": 350,
					"code": "J"
				}, {
					"name": "金华",
					"id": 337,
					"code": "J"
				}, {
					"name": "乐清",
					"id": 353,
					"code": "L"
				}, {
					"name": "龙泉",
					"id": 365,
					"code": "L"
				}, {
					"name": "丽水",
					"id": 342,
					"code": "L"
				}, {
					"name": "宁波",
					"id": 312,
					"code": "N"
				}, {
					"name": "宁海",
					"id": 360,
					"code": "N"
				}, {
					"name": "平湖",
					"id": 347,
					"code": "P"
				}, {
					"name": "衢州",
					"id": 341,
					"code": "Q"
				}, {
					"name": "瑞安",
					"id": 356,
					"code": "R"
				}, {
					"name": "绍兴",
					"id": 336,
					"code": "S"
				}, {
					"name": "上虞",
					"id": 358,
					"code": "S"
				}, {
					"name": "三门",
					"id": 361,
					"code": "S"
				}, {
					"name": "桐乡",
					"id": 355,
					"code": "T"
				}, {
					"name": "台州",
					"id": 338,
					"code": "T"
				}, {
					"name": "温岭",
					"id": 357,
					"code": "W"
				}, {
					"name": "温州",
					"id": 324,
					"code": "W"
				}, {
					"name": "象山",
					"id": 363,
					"code": "X"
				}, {
					"name": "永嘉",
					"id": 354,
					"code": "Y"
				}, {
					"name": "玉环县",
					"id": 346,
					"code": "Y"
				}, {
					"name": "永康",
					"id": 348,
					"code": "Y"
				}, {
					"name": "余姚",
					"id": 351,
					"code": "Y"
				}, {
					"name": "义乌",
					"id": 344,
					"code": "Y"
				}, {
					"name": "诸暨",
					"id": 359,
					"code": "Z"
				}, {
					"name": "舟山",
					"id": 343,
					"code": "Z"
				}]
			}]

var letterJson = {"A":[],"B":[],"C":[],"D":[],"E":[],"F":[],"G":[],"H":[],"J":[],"K":[],"L":[],"M":[],"N":[],"P":[],"Q":[],"R":[],"S":[],"T":[],"W":[],"X":[],"Y":[],"Z":[]}
   ,hotCity = [{id: '', name: '全国'
		},{id: '7', name: '北京'
		},{id: '26', name: '上海'
		},{id: '111', name: '广州'
		},{id: '174', name: '深圳'
		},{id: '984', name: '成都'
		},{id: '297', name: '杭州'
		},{id: '659', name: '全国'
		}, {id:'210', name: '武汉'
		}, {id:'789', name: '大连'
		}, {id:'773', name: '沈阳'
		}, {id:'620', name: '哈尔滨'
		}]
   ,html = ''
   ,htmH = ''
   ,i,j,t,temp;	

   for(i = 0, j = citylist.length;i<j;i++) {
   	var t = citylist[i].children;
   	for (var k = 0,n = t.length;k<n;k++) {
   		temp = t[k];
   		letterJson[temp.code].push({
   			"id":temp.id,
   			"name":temp.name
   		})
   	}
   }

    html +='<h4><a href="javascript:;" name="hot">热门城市</a></h4>'
    html +='<ul class="col-xs-11"  id="hotCity">';
    for (i = 0,j = hotCity.length; i<j;i++) {
    	t = hotCity[i];
    	html +='<li data-id="'+ t.id +'" data-name="'+ t.name +'">' + t.name + '</li>';
    }
    html +='</ul>';
    // console.log(1)
    $('.hotC').append(html);

    for (var i in letterJson) if(letterJson.hasOwnProperty(i)) {
    	t = letterJson[i];
    	htmH +='<h4><a href="javascript:;" name="'+ i +'">' + i +  '</a></h4>';
    	for ( k in t) if (t.hasOwnProperty(k)) {
    		temp = t[k];
    		htmH +='<li data-id="' +temp.id + '" data-name="' + temp.name +'" >' + temp.name + '</li>';
    	}
    }
	$('#cityUl').append(htmH);

	$(document).on('click','li',function(){
		$(this).parents('.container').find('li').removeClass('green');
		$(this).addClass('green');
	})

	$('.city_btn').on('click',function(e){
		e.preventDefault();
		if($('.container li').hasClass('green')){
			//ajax
			alert(1)
		}else {
			alert('?');
		}
	})

});							

